"""
Working memory: the active context of one AI coding agent task.

This memory exists only during the current task execution.
It stores everything the agent needs while it:
- understands the request
- creates or uses a sandbox environment
- modifies code
- runs tests
- verifies the result

Working memory is NEVER persisted.
If information needs to survive after this task, it belongs
in session memory or long-term memory.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict


@dataclass
class EnvironmentState:
    """
    Temporary state of the disposable environment where the agent runs.

    This represents the machine/container the agent is using to test
    and verify changes.
    """

    environment_id: Optional[str] = None
    operating_system: Optional[str] = None

    runtime_versions: Dict[str, str] = field(default_factory=dict)

    installed_dependencies: List[str] = field(default_factory=list)

    commands_executed: List[str] = field(default_factory=list)

    status: Optional[str] = None
    # Examples:
    # creating
    # running
    # failed
    # destroyed


@dataclass
class WorkingMemory:
    """
    One AI coding agent task's active context.

    Created when a task begins and discarded when it finishes.
    """

    # User request + code context
    code: str
    language: str

    task_description: Optional[str] = None
    file_path: Optional[str] = None

    # Error understanding
    error_message: Optional[str] = None
    issues_found: Optional[list] = None
    severity: Optional[str] = None
    explanation: Optional[str] = None


    # Agent actions
    suggested_fix: Optional[str] = None
    rewritten_code: Optional[str] = None

    tests_generated: Optional[list] = None

    commands_run: List[str] = field(default_factory=list)


    # Sandbox/environment information
    environment: EnvironmentState = field(
        default_factory=EnvironmentState
    )


    # Verification lifecycle

    verification_status: Optional[str] = None
    # Examples:
    # pending
    # running
    # passed
    # failed


    verification_evidence: Dict = field(
        default_factory=dict
    )
    """
    Stores proof generated by the agent.

    Example:

    {
        "screenshots": [
            "homepage.png"
        ],
        "recordings": [
            "test_run.mp4"
        ],
        "logs": [
            "build_success.log"
        ]
    }
    """


    # Memory retrieved from other layers

    memory_context: str = field(default="")


    # Agent reasoning metadata

    current_step: Optional[str] = None
    """
    Examples:

    analyzing
    creating_environment
    installing_dependencies
    running_tests
    verifying
    completed
    """


    def error_signature(self) -> str:
        """
        Creates a reusable identifier for similar failures.

        Used by long-term memory to find previous successful fixes.
        """

        basis = (
            self.error_message
            or (
                self.issues_found[0]
                if self.issues_found
                else ""
            )
            or ""
        )

        first_line = (
            basis.strip().splitlines()[0]
            if basis.strip()
            else "unknown"
        )

        return f"{self.language}:{first_line[:120]}"